[sncast.default]
url = "https://starknet-sepolia-rpc.publicnode.com"

[[sncast.default.accounts]]
name = "deployer"
address = "0x73551d509481e49390d1e3242ebbdca86dc070b1c8b07dda3d94a6155ee8813"
private_key_path = "~/.starkli-wallets/deployer/private_key.txt"
type = "argent"
active = true
